# Generated by Django 4.0.3 on 2022-03-24 13:45

import account.model_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=account.model_fields.LowercaseEmailField(max_length=254, unique=True),
        ),
    ]
