# Generated by Django 4.0.3 on 2022-03-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userconfirmcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmcode',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
