# Generated by Django 4.0.3 on 2022-03-26 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userconfirmcode_sended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmcode',
            name='sended',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
