# Generated by Django 4.0.3 on 2022-03-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0002_shortener_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='short_url',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
