# Generated by Django 4.0.3 on 2022-03-26 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0003_alter_shortener_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortener',
            name='used',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
